document.write("<div class=\"sidenav\">");
document.write("        <a href=\"index.html\">Home<\/a>");
document.write("        <a href=\"academics.html\">Academics<\/a>");
document.write("        <a href=\"work.html\">Work<\/a>");
document.write("        <a href=\"sports.html\">Sports<\/a>");
document.write("        <a href=\"gap_year.html\">Gap Year<\/a>");
document.write("        <a href=\"fun.html\">Fun<\/a>");
document.write("");
document.write("        <div class=\"social-media-icons\">");
document.write("            <a href=\"https:\/\/facebook.com\/upanshu.lakhani\" role=\"button\" target=\"_blank\">");
document.write("                <i class=\"fa fa-facebook\"><\/i>");
document.write("            <\/a>");
document.write("");
document.write("            <a href=\"https:\/\/twitter.com\/CricGameMeme\" role=\"button\" target=\"_blank\">");
document.write("                <i class=\"fa fa-twitter\"><\/i>");
document.write("            <\/a>");
document.write("");
document.write("            <a href=\"https:\/\/github.com\/upanshu1310\" role=\"button\" target=\"_blank\">");
document.write("                <i class=\"fa fa-github\"><\/i>");
document.write("            <\/a>");
document.write("");
document.write("            <a href=\"https:\/\/www.instagram.com\/upanshu__\" role=\"button\" target=\"_blank\">");
document.write("                <i class=\"fa fa-instagram\"><\/i>");
document.write("            <\/a>");
document.write("        <\/div>");
document.write("");
document.write("    <\/div>");